### ISSUE TITLE
Error on Windows?

### ISSUE THREAD

**Issue by rgdelato** [rgdelato/linter-joker#4]
Reported by @dave.dixon:

```
[Linter] Error running joker Error: Process execution timed out
    at C:\Users\dave\.atom\packages\linter-joker\node_modules\sb-exec\lib\index.js:89:18
(anonymous) @ C:\Users\dave\.atom\packages\linter\lib\linter-registry.js:159
```

**Comment by sparkofreason** [comment]
Problem looks to be with joker. Running "joker --lint t_core.clj" from the command line takes a long time, gives no output.

**Comment by sparkofreason** [comment]
Submitted https://github.com/candid82/joker/issues/19. This problem disappears if I make a .joker file. Working now.

**Comment by rgdelato** [comment]
Fixed by https://github.com/candid82/joker/issues/19
