### ISSUE TITLE
Parse error in .joker file

### ISSUE THREAD

**Issue by monoburn** [rgdelato/linter-joker#5]
I added a .joker file to avoid a warning about unused namespace:
```
{:ignored-unused-namespaces [my.namespace]}
```
The warning disappeared as expected but I get a Parse error in the .joker file itself: Unable to resolve symbol: my.namespace.

Is there any way to avoid it? Like disable linting of the .joker file? https://github.com/rgdelato/linter-joker/blob/master/index.js mentions the .joke extension. Should that be .joker?

Regards,
Erik Severinsen

**Comment by Cortys** [comment]
I just created a PR #6 with a simple fix for this issue.
