### ISSUE TITLE
Not working wiht Atom 1.31.1?

### ISSUE THREAD

**Issue by jacekschae** [rgdelato/linter-joker#8]
I don't know if this is me or if something changed with how this plugin works?

I have the joker installed 
```shell
which joker
/usr/local/bin/joker
```

and the plugin `linter-joker` but somehow the files are not lint. 
When I lint them at command line with `joker --lint <filename>` everything seems to be working.

I also try to provide the path in the plugin Settings - `Joker path` but that doesn't work as well

Am I missing something?

**Comment by jurka** [comment]
There are pending pull request #7 .

**Comment by seancorfield** [comment]
I had to downgrade back to Joker 0.9.2 (my previously installed version) to get this working -- due to the changes as of 0.9.6.

**Comment by rgdelato** [comment]
Pull request #7 should now be merged and published, let me know if that fixes the issue!

**Comment by seancorfield** [comment]
(sorry, I realized that this was the wrong end of the problem -- thank you for updating this!)

**Comment by jacekschae** [comment]
Works pretty good! Thanks!
